
export default {
"death.attack.anvil":"%diedplayer%は落下してきた金床に押しつぶされた",
"death.attack.arrow":"%diedplayer%は%killer%に射抜かれた",
"death.attack.arrow.item":"%diedplayer%は%killer%の%item%で射抜かれた",
"death.attack.bullet":"%diedplayer%は%killer%に狙撃された",
"death.attack.cactus":"%diedplayer%はサボテンが刺さって死んだ",
"death.attack.cactus.player":"%diedplayer%は%killer%から逃げようとしてサボテンにぶつかった",
"death.attack.dehydration":"%diedplayer% が脱水症状で死亡",
"death.attack.drown":"%diedplayer%は溺れ死んだ",
"death.attack.drown.player":"%diedplayer%は%killer%から逃れようとして溺れ死んだ",
"death.attack.explosion":"%diedplayer%は爆発に巻き込まれた",
"death.attack.explosion.by.bed":"%diedplayer% は[意図的なゲーム デザイン]に倒された",
"death.attack.explosion.player":"%diedplayer%は%killer%に爆破された",
"death.attack.fall":"%diedplayer%は地面に強く激突した",
"death.attack.fallingBlock":"%diedplayer%は落下してきたブロックに押しつぶされた",
"death.attack.fireball":"%diedplayer%は%killer%に火だるまにされた",
"death.attack.fireball.item":"%diedplayer%は%killer%の%item%で火だるまにされた",
"death.attack.fireworks":"%diedplayer%は花火の爆発に巻き込まれた",
"death.attack.flyIntoWall":"%diedplayer%は運動エネルギーを体験した",
"death.attack.generic":"%diedplayer%は死んだ",
"death.attack.indirectMagic":"%diedplayer%は%killer%の魔法で殺された",
"death.attack.indirectMagic.item":"%diedplayer%は%killer%の%item%で殺された",
"death.attack.inFire":"%diedplayer%は炎に巻かれた",
"death.attack.inFire.player":"%diedplayer%は%killer%と戦いながら火の中へ踏み入った",
"death.attack.inWall":"%diedplayer%は壁の中で窒息した",
"death.attack.lava":"%diedplayer%は溶岩遊泳を試みた",
"death.attack.lava.player":"%diedplayer%は%killer%から逃れようと溶岩遊泳を試みた",
"death.attack.lightningBolt":"%diedplayer%は雷に打たれた",
"death.attack.maceSmash.player":"%diedplayer%は%killer%に粉砕された",
"death.attack.maceSmash.player.item":"%diedplayer% は %killer% に %item% で粉砕された",
"death.attack.magic":"%diedplayer%は魔法で殺された",
"death.attack.magma":"%diedplayer% は足元が溶岩だと気づいた",
"death.attack.magma.player":"%diedplayer% は %killer% のせいで危険な領域を歩いた",
"death.attack.mob":"%diedplayer%は%killer%に殺害された",
"death.attack.mob.item":"%diedplayer%は%killer%の%item%で殺害された",
"death.attack.onFire":"%diedplayer%はこんがりと焼けた",
"death.attack.onFire.player":"%diedplayer%は%killer%と戦いながらカリカリに焼けた",
"death.attack.outOfWorld":"%diedplayer%は奈落の底へ落ちた",
"death.attack.player":"%diedplayer%は%killer%に殺害された",
"death.attack.player.item":"%diedplayer%は%killer%の%item%で殺害された",
"death.attack.spit":"%diedplayer%は%killer%に丸めてポイされた",
"death.attack.starve":"%diedplayer%は飢え死にした",
"death.attack.sweetBerry":"%diedplayer%はスイートベリーの棘が刺さって死んだ",
"death.attack.thorns":"%diedplayer%は%killer%を傷つけようとして殺された",
"death.attack.thrown":"%diedplayer%は%killer%によってぺしゃんこにされた",
"death.attack.thrown.item":"%diedplayer%は%killer%の%item%でぺしゃんこにされた",
"death.attack.trident":"%diedplayer%は%killer%に刺殺された",
"death.attack.wither":"%diedplayer%は干からびた",
"death.attack.freeze":"%diedplayer%は凍え死んだ",
"death.attack.sonicBoom":"%diedplayer%は衝撃波に消し飛ばされた",
"death.attack.sonicBoom.player":"%diedplayer%は%killer%から逃れようとして衝撃波に消し飛ばされた",
"death.attack.stalactite":"%diedplayer%は落ちてきた鍾乳石に串刺しにされた",
"death.attack.stalagmite":"%diedplayer%は石筍に突き刺さった",
"death.fell.accident.generic":"%diedplayer%は高い所から落ちた",
"death.fell.accident.ladder":"%diedplayer%ははしごから落ちた",
"death.fell.accident.vines":"%diedplayer%はツタから滑り落ちた",
"death.fell.accident.water":"%diedplayer% は水から落ちた",
"death.fell.assist":"%diedplayer%は%killer%に落とされる運命だった",
"death.fell.assist.item":"%diedplayer%は%killer%の%item%で落とされる運命だった",
"death.fell.finish":"%diedplayer%は高いところから落下し、%killer%によってとどめを刺された",
"death.fell.finish.item":"%diedplayer%は高いところから落下し、%killer%の%item%によってとどめを刺された",
"death.fell.killer":"%diedplayer%は落ちる運命だった"
}